<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ta"
    nsURI="http://ta/1.0" nsPrefix="ta">
  <eClassifiers xsi:type="ecore:EClass" name="name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nom" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="timed_automata" eSuperTypes="#//name">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="1"
        upperBound="-1" eType="#//state" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="clocks" lowerBound="1"
        eType="#//clock" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gard" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="action" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//state"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="reset" lowerBound="1" upperBound="-1"
        eType="#//clock"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="state" eSuperTypes="#//name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="invariant" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="clock" eSuperTypes="#//name">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
